require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/routes.rb"

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc"]

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]

Performance/BlockGivenWithExplicitBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/UnlessLogicalOperators:
  EnforcedStyle: forbid_logical_operators
