services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ypfo_${RAILS_ENV}

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=${RAILS_ENV}
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes:
  db-data:
