services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ypfo_development

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
