default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV["POSTGRES_PORT"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: ypfo_development

test:
  <<: *default
  database: ypfo_test

production:
  <<: *default
  database: ypfo_production
  username: ypfo
  password: <%= ENV["YPFO_DATABASE_PASSWORD"] %>
